# Generated by Django 5.0.6 on 2024-06-28 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_alter_save_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='save',
            new_name='Contact',
        ),
    ]
